### ISSUE TITLE
Add loading screen for signup/login 

### ISSUE THREAD

**Issue by silenteyesoncode** [The-Unleashed-Club/openMind#11]
## Description 🚀

The issue at hand is a complex one that requires careful consideration and thoughtful analysis in order to be fully understood. At its core, it involves understanding the various components that are at play and how they interact and affect one another. It is important to take the time to consider all aspects of the issue in order to gain a clear, concise description of what it is about and how it can be addressed. A thorough, in-depth exploration of the matter is necessary in order to arrive at the best possible

## Files 🚨

A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

## Screenshots 📸

<img src="paste_the_URL" width="350">

## To Reproduce ✅

If this issue is describing a bug, include some steps to reproduce the behavior.

## Task

- Introduce redux
- Add loading state 
- write the reducer accordingly

**Comment by silenteyesoncode** [comment]
You are welcome to contribute by working on the branch mentioned: 
https://github.com/The-Unleashed-Club/openMind/tree/Loading-screen-auth. 

Before proceeding, please ensure that you carefully review and adhere to the guidelines outlined in the [contribution.md](https://github.com/The-Unleashed-Club/openMind/blob/Loading-screen-auth/Contributing.md) file.

**Comment by mtalhabaig3** [comment]
Acknowledged!

**Comment by silenteyesoncode** [comment]
@all-contributors please add @mtalhabaig3 for code
