### ISSUE TITLE
Re-design CreateImage.js

### ISSUE THREAD

**Issue by silenteyesoncode** [The-Unleashed-Club/openMind#20]
## Description 🚀

redesign [createimage.js](https://github.com/The-Unleashed-Club/openMind/blob/main/src/Screens/createimage.js) as according to [createchat.js](https://github.com/The-Unleashed-Club/openMind/blob/main/src/Screens/createchat.js)

## Files 🚨

/main/src/Screens/createimage.js

## Screenshots 📸

<img src="paste_the_URL" width="350">

## To Reproduce ✅

createimage screen

## Task

study createchat screen and make a same css for createimage screen

**Comment by Aryan123-rgb** [comment]
Well I am facing difficulty in understanding the context of this issue. Both of the files look same to me only one has extra spaces in it while the other one doesn't, do you want me to fix that. If not please explain to me what is the issue what I as a contributor can contribute?

**Comment by Aryan123-rgb** [comment]
@silenteyesoncode the app is not responding. It's just stuck after bundling all the resources

**Comment by silenteyesoncode** [comment]
Try run run it locally

- if you see in [createchat.js](https://github.com/The-Unleashed-Club/openMind/blob/main/src/Screens/createchat.js) have different styling than [createimage.js](https://github.com/The-Unleashed-Club/openMind/blob/main/src/Screens/createimage.js) 
    ``` 
    container: {
        flex: 1,
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: "3.5%",
        paddingTop: "12%",
        backgroundColor: colors.backgroundColor,
      },
    ```

- In [createchat.js](https://github.com/The-Unleashed-Club/openMind/blob/main/src/Screens/createchat.js) we are also using an svg icon the a response of openAI bot 

perhaps these are some very small UI changes need to be updated in [createimage.js](https://github.com/The-Unleashed-Club/openMind/blob/main/src/Screens/createimage.js) I believe for beginners its easy make PR 

If you wanna 1:1 call for further explanation feel free to book a call here with [Calendly ](https://calendly.com/7silenteyes07/professional-coffee-chat)

**Comment by Coding-Algorithm** [comment]
Is this issue free for contribution?

**Comment by silenteyesoncode** [comment]
yes it is
@Coding-Algorithm

**Comment by Coding-Algorithm** [comment]
I have started working on this.

**Comment by silenteyesoncode** [comment]
### I guess we are not using paid account for **public repos**
 

- Please create a rapid API account for this, And your own token for test   
We are using [Open AI](https://rapidapi.com/openai-api-openai-api-default/api/openai80/) for this 

I surely mention this in my contribution.md

**Comment by Coding-Algorithm** [comment]
Ok. I missed that.

I would look into creating an account to get an API key to test with.

**Comment by silenteyesoncode** [comment]
@all-contributors please add @Coding-Algorithm for code

**Comment by Coding-Algorithm** [comment]
> @all-contributors please add @Coding-Algorithm for code

Thanks, appreciates this.
